version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_api"
    ports:
      - "3306:3306"
    volumes:
      - /home/leo/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - mysql-compose-network
networks: 
  mysql-compose-network:
    driver: bridge